"""
Adapter protocol definitions for BlazeORM.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, Sequence

from ..dialects.base import Dialect


@dataclass(slots=True)
class ConnectionConfig:
    """
    Normalized connection configuration for adapters.
    """

    url: str
    autocommit: bool = False
    isolation_level: str | None = None
    timeout: float | None = None
    options: dict[str, Any] | None = None


class DatabaseAdapter(Protocol):
    """
    Adapter interface exposing database operations used by higher layers.
    """

    dialect: Dialect

    def connect(self, config: ConnectionConfig) -> Any:
        """
        Establish a connection handle using the supplied configuration.
        """

    def close(self) -> None:
        """
        Close underlying resources. Implementations should be idempotent.
        """

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> Any:
        """
        Execute a single SQL statement returning a cursor-like object.
        """

    def executemany(self, sql: str, seq_of_params: Sequence[Sequence[Any]]) -> Any:
        """
        Execute a prepared statement against multiple parameter sets.
        """

    def begin(self) -> None:
        """
        Start a transaction or savepoint as appropriate for the backend.
        """

    def commit(self) -> None:
        """
        Commit the current transaction context.
        """

    def rollback(self) -> None:
        """
        Roll back the current transaction context.
        """

    def last_insert_id(self, cursor: Any, table: str, pk_column: str) -> Any:
        """
        Retrieve the primary key value generated by the previous insert.
        """
